---
version: "3.3"
services:
  db:
    image: dockerdeepak/workshop:pgdb
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    container_name: pgdb
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080
  developer:
    image: dockerdeepak/workshop:jdk17_mvn_go
    restart: always
    ports:
      - 9080:9090
      - 9443:9443
      - 7777:7777
      - 9090:8080
      - 5005:5005
    container_name: myapp
