---
version: "3.3"
services:
  db:
    image: dockerdeepak/workshop:pgdb
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    container_name: pgdb
  developer:
    image: dockerdeepak/workshop:jdk11_mvn_go
    restart: always
    ports:
      - 9080:9080
      - 7777:7777
      - 8080:8080
      - 5005:5005
    container_name: myapp
